blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/FngNHpbcY7
    about: Get help from our active discord community. The plugin author is very active there too!
